version: '3.1'
services:
    web:
        image: cmilanf/dockersamples:languages-1.0-debug
        deploy:
            mode: replicated
            replicas: 2
        healthcheck:
            interval: 10s
            timeout: 5s
            retries: 3
        ports:
            - 5000:5000
            - 7000:7000
        environment:
            DB: 'db'
            THREADED: 'True'
        networks:
            - backend

    db:
        image: consul:0.7.2
        command: agent -server -ui -client=0.0.0.0 -bootstrap-expect=2 -retry-join=db -retry-join=db -retry-join=db -retry-interval 5s
        deploy:
            replicas: 2
        ports:
            - 8500:8500 
        environment:
            CONSUL_BIND_INTERFACE: 'eth2'
            CONSUL_LOCAL_CONFIG: '{"skip_leave_on_interrupt": true}'
        networks: 
            - backend
      
networks:
    backend:





